#############################################################################
# Makefile for building: ZSpireGameEd
# Generated by qmake (3.1) (Qt 5.12.4)
# Project:  ZSpireGameEd.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ZSpireGameEd.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/freetype2 -isystem /usr/include/bullet -I/home/andrew/ZSPIRE/zsgamedit/../Engine/headers -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ZSpireGameEd1.0.0
DISTDIR = /home/andrew/ZSPIRE/zsgamedit/.tmp/ZSpireGameEd1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lGLEW -lSDL2 -lopenal -llua5.3 -lassimp -lz -lfreetype -lBulletSoftBody -lBulletDynamics -lBulletCollision -lLinearMath -L/home/andrew/ZSPIRE/zsgamedit/../build-ZSpireEngine-Desktop-Debug/ -lzsengine -lvulkan /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwin.cpp \
		ProjEd/ProjectEdit.cpp \
		Render/zs-shader.cpp \
		Render/zs-math.cpp \
		Render/zs-pipeline.cpp \
		Render/zs-mesh.cpp \
		Render/zs-texture.cpp \
		World/World.cpp \
		World/Misc.cpp \
		ProjEd/InspectorWin.cpp \
		ProjEd/ProjCreateWin.cpp \
		World/zs-camera.cpp \
		ProjEd/PropertyAreas.cpp \
		ProjEd/EdActions.cpp \
		Misc/oal_manager.cpp \
		ProjEd/EditorUI.cpp \
		Misc/ProjBuilder.cpp \
		Scripting/LuaScript.cpp \
		Scripting/zsensdk.cpp \
		Render/MatShaderProps.cpp \
		World/GameObject.cpp \
		World/GoProperty/go_filestream.cpp \
		World/GoProperty/go_properties.cpp \
		World/GoProperty/tile_properties.cpp \
		Misc/AssimpMeshLoader.cpp \
		Render/GizmosRenderer.cpp \
		Misc/GlyphManager.cpp \
		Misc/EditorManager.cpp \
		Scripting/zsensdk_input.cpp \
		ProjEd/EditorSettings.cpp \
		World/TerrainUtils.cpp \
		World/Physics.cpp \
		Misc/ThumbnailsMaster.cpp \
		Render/zs-animation.cpp \
		Misc/zs3m-master.cpp \
		ui/zs-uiwidget.cpp \
		ui/zs-uibutton.cpp \
		Render/zs-material-defines.cpp \
		Input/zs-input.cpp moc_mainwin.cpp \
		moc_ProjectEdit.cpp \
		moc_InspectorWin.cpp \
		moc_ProjCreateWin.cpp \
		moc_ProjBuilder.cpp \
		moc_InspEditAreas.cpp
OBJECTS       = main.o \
		mainwin.o \
		ProjectEdit.o \
		zs-shader.o \
		zs-math.o \
		zs-pipeline.o \
		zs-mesh.o \
		zs-texture.o \
		World.o \
		Misc.o \
		InspectorWin.o \
		ProjCreateWin.o \
		zs-camera.o \
		PropertyAreas.o \
		EdActions.o \
		oal_manager.o \
		EditorUI.o \
		ProjBuilder.o \
		LuaScript.o \
		zsensdk.o \
		MatShaderProps.o \
		GameObject.o \
		go_filestream.o \
		go_properties.o \
		tile_properties.o \
		AssimpMeshLoader.o \
		GizmosRenderer.o \
		GlyphManager.o \
		EditorManager.o \
		zsensdk_input.o \
		EditorSettings.o \
		TerrainUtils.o \
		Physics.o \
		ThumbnailsMaster.o \
		zs-animation.o \
		zs3m-master.o \
		zs-uiwidget.o \
		zs-uibutton.o \
		zs-material-defines.o \
		zs-input.o \
		moc_mainwin.o \
		moc_ProjectEdit.o \
		moc_InspectorWin.o \
		moc_ProjCreateWin.o \
		moc_ProjBuilder.o \
		moc_InspEditAreas.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ZSpireGameEd.pro mainwin.h \
		ProjEd/headers/ProjectEdit.h \
		Render/headers/zs-shader.h \
		Render/headers/zs-math.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-mesh.h \
		Render/headers/zs-texture.h \
		World/headers/World.h \
		World/headers/Misc.h \
		ProjEd/headers/InspectorWin.h \
		ProjEd/headers/ProjCreateWin.h \
		World/headers/zs-camera.h \
		World/headers/2dtileproperties.h \
		ProjEd/headers/EdActions.h \
		Misc/headers/oal_manager.h \
		Misc/headers/ProjBuilder.h \
		include_engine.h \
		Scripting/headers/LuaScript.h \
		Scripting/headers/zsensdk.h \
		World/headers/obj_properties.h \
		ProjEd/headers/InspEditAreas.h \
		triggers.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/zs_types.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/EditorManager.h \
		ProjEd/headers/EditorSettings.h \
		World/headers/terrain.h \
		Misc/headers/ThumbnailsMaster.h \
		Render/headers/zs-animation.h \
		Misc/headers/zs3m-master.h \
		ui/headers/zs-uiwidget.h \
		ui/headers/zs-uibutton.h \
		Input/headers/zs-input.h main.cpp \
		mainwin.cpp \
		ProjEd/ProjectEdit.cpp \
		Render/zs-shader.cpp \
		Render/zs-math.cpp \
		Render/zs-pipeline.cpp \
		Render/zs-mesh.cpp \
		Render/zs-texture.cpp \
		World/World.cpp \
		World/Misc.cpp \
		ProjEd/InspectorWin.cpp \
		ProjEd/ProjCreateWin.cpp \
		World/zs-camera.cpp \
		ProjEd/PropertyAreas.cpp \
		ProjEd/EdActions.cpp \
		Misc/oal_manager.cpp \
		ProjEd/EditorUI.cpp \
		Misc/ProjBuilder.cpp \
		Scripting/LuaScript.cpp \
		Scripting/zsensdk.cpp \
		Render/MatShaderProps.cpp \
		World/GameObject.cpp \
		World/GoProperty/go_filestream.cpp \
		World/GoProperty/go_properties.cpp \
		World/GoProperty/tile_properties.cpp \
		Misc/AssimpMeshLoader.cpp \
		Render/GizmosRenderer.cpp \
		Misc/GlyphManager.cpp \
		Misc/EditorManager.cpp \
		Scripting/zsensdk_input.cpp \
		ProjEd/EditorSettings.cpp \
		World/TerrainUtils.cpp \
		World/Physics.cpp \
		Misc/ThumbnailsMaster.cpp \
		Render/zs-animation.cpp \
		Misc/zs3m-master.cpp \
		ui/zs-uiwidget.cpp \
		ui/zs-uibutton.cpp \
		Render/zs-material-defines.cpp \
		Input/zs-input.cpp
QMAKE_TARGET  = ZSpireGameEd
DESTDIR       = 
TARGET        = ZSpireGameEd


first: all
####### Build rules

ZSpireGameEd: /usr/lib/libzsengine.a ui_mainwin.h ui_editor.h ui_inspector_win.h ui_proj_create_win.h ui_buildconsole.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ZSpireGameEd.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ZSpireGameEd.pro
	$(QMAKE) -o Makefile ZSpireGameEd.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
ZSpireGameEd.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ZSpireGameEd.pro

qmake_all: FORCE


all: Makefile ZSpireGameEd

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwin.h ProjEd/headers/ProjectEdit.h Render/headers/zs-shader.h Render/headers/zs-math.h Render/headers/zs-pipeline.h Render/headers/zs-mesh.h Render/headers/zs-texture.h World/headers/World.h World/headers/Misc.h ProjEd/headers/InspectorWin.h ProjEd/headers/ProjCreateWin.h World/headers/zs-camera.h World/headers/2dtileproperties.h ProjEd/headers/EdActions.h Misc/headers/oal_manager.h Misc/headers/ProjBuilder.h include_engine.h Scripting/headers/LuaScript.h Scripting/headers/zsensdk.h World/headers/obj_properties.h ProjEd/headers/InspEditAreas.h triggers.h Render/headers/MatShaderProps.h Misc/headers/zs_types.h Misc/headers/AssimpMeshLoader.h Render/headers/GizmosRenderer.h Misc/headers/GlyphManager.h Misc/headers/EditorManager.h ProjEd/headers/EditorSettings.h World/headers/terrain.h Misc/headers/ThumbnailsMaster.h Render/headers/zs-animation.h Misc/headers/zs3m-master.h ui/headers/zs-uiwidget.h ui/headers/zs-uibutton.h Input/headers/zs-input.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwin.cpp ProjEd/ProjectEdit.cpp Render/zs-shader.cpp Render/zs-math.cpp Render/zs-pipeline.cpp Render/zs-mesh.cpp Render/zs-texture.cpp World/World.cpp World/Misc.cpp ProjEd/InspectorWin.cpp ProjEd/ProjCreateWin.cpp World/zs-camera.cpp ProjEd/PropertyAreas.cpp ProjEd/EdActions.cpp Misc/oal_manager.cpp ProjEd/EditorUI.cpp Misc/ProjBuilder.cpp Scripting/LuaScript.cpp Scripting/zsensdk.cpp Render/MatShaderProps.cpp World/GameObject.cpp World/GoProperty/go_filestream.cpp World/GoProperty/go_properties.cpp World/GoProperty/tile_properties.cpp Misc/AssimpMeshLoader.cpp Render/GizmosRenderer.cpp Misc/GlyphManager.cpp Misc/EditorManager.cpp Scripting/zsensdk_input.cpp ProjEd/EditorSettings.cpp World/TerrainUtils.cpp World/Physics.cpp Misc/ThumbnailsMaster.cpp Render/zs-animation.cpp Misc/zs3m-master.cpp ui/zs-uiwidget.cpp ui/zs-uibutton.cpp Render/zs-material-defines.cpp Input/zs-input.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwin.ui ProjEd/ui/editor.ui ProjEd/ui/inspector_win.ui ProjEd/ui/proj_create_win.ui ProjEd/ui/buildconsole.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwin.cpp moc_ProjectEdit.cpp moc_InspectorWin.cpp moc_ProjCreateWin.cpp moc_ProjBuilder.cpp moc_InspEditAreas.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwin.cpp moc_ProjectEdit.cpp moc_InspectorWin.cpp moc_ProjCreateWin.cpp moc_ProjBuilder.cpp moc_InspEditAreas.cpp
moc_mainwin.cpp: mainwin.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		ProjEd/headers/ProjCreateWin.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/andrew/ZSPIRE/zsgamedit/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/andrew/ZSPIRE/zsgamedit -I/usr/include/freetype2 -I/usr/include/bullet -I/home/andrew/ZSPIRE/Engine/headers -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwin.h -o moc_mainwin.cpp

moc_ProjectEdit.cpp: ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/andrew/ZSPIRE/zsgamedit/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/andrew/ZSPIRE/zsgamedit -I/usr/include/freetype2 -I/usr/include/bullet -I/home/andrew/ZSPIRE/Engine/headers -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ProjEd/headers/ProjectEdit.h -o moc_ProjectEdit.cpp

moc_InspectorWin.cpp: ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/andrew/ZSPIRE/zsgamedit/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/andrew/ZSPIRE/zsgamedit -I/usr/include/freetype2 -I/usr/include/bullet -I/home/andrew/ZSPIRE/Engine/headers -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ProjEd/headers/InspectorWin.h -o moc_InspectorWin.cpp

moc_ProjCreateWin.cpp: ProjEd/headers/ProjCreateWin.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/andrew/ZSPIRE/zsgamedit/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/andrew/ZSPIRE/zsgamedit -I/usr/include/freetype2 -I/usr/include/bullet -I/home/andrew/ZSPIRE/Engine/headers -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ProjEd/headers/ProjCreateWin.h -o moc_ProjCreateWin.cpp

moc_ProjBuilder.cpp: Misc/headers/ProjBuilder.h \
		Misc/headers/zs_types.h \
		ui_buildconsole.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/andrew/ZSPIRE/zsgamedit/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/andrew/ZSPIRE/zsgamedit -I/usr/include/freetype2 -I/usr/include/bullet -I/home/andrew/ZSPIRE/Engine/headers -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Misc/headers/ProjBuilder.h -o moc_ProjBuilder.cpp

moc_InspEditAreas.cpp: ProjEd/headers/InspEditAreas.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/andrew/ZSPIRE/zsgamedit/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/andrew/ZSPIRE/zsgamedit -I/usr/include/freetype2 -I/usr/include/bullet -I/home/andrew/ZSPIRE/Engine/headers -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ProjEd/headers/InspEditAreas.h -o moc_InspEditAreas.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwin.h ui_editor.h ui_inspector_win.h ui_proj_create_win.h ui_buildconsole.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwin.h ui_editor.h ui_inspector_win.h ui_proj_create_win.h ui_buildconsole.h
ui_mainwin.h: mainwin.ui \
		/usr/lib/qt5/bin/uic \
		mainwin.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		ProjEd/headers/ProjCreateWin.h
	/usr/lib/qt5/bin/uic mainwin.ui -o ui_mainwin.h

ui_editor.h: ProjEd/ui/editor.ui \
		/usr/lib/qt5/bin/uic \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h
	/usr/lib/qt5/bin/uic ProjEd/ui/editor.ui -o ui_editor.h

ui_inspector_win.h: ProjEd/ui/inspector_win.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ProjEd/ui/inspector_win.ui -o ui_inspector_win.h

ui_proj_create_win.h: ProjEd/ui/proj_create_win.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ProjEd/ui/proj_create_win.ui -o ui_proj_create_win.h

ui_buildconsole.h: ProjEd/ui/buildconsole.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ProjEd/ui/buildconsole.ui -o ui_buildconsole.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwin.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		ProjEd/headers/ProjCreateWin.h \
		Input/headers/zs-input.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwin.o: mainwin.cpp mainwin.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		ProjEd/headers/ProjCreateWin.h \
		ui_mainwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwin.o mainwin.cpp

ProjectEdit.o: ProjEd/ProjectEdit.cpp ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		ProjEd/headers/InspEditAreas.h \
		World/headers/obj_properties.h \
		Scripting/headers/LuaScript.h \
		World/headers/terrain.h \
		World/headers/2dtileproperties.h \
		ui_editor.h \
		mainwin.h \
		ProjEd/headers/ProjCreateWin.h \
		Misc/headers/zs3m-master.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProjectEdit.o ProjEd/ProjectEdit.cpp

zs-shader.o: Render/zs-shader.cpp Render/headers/zs-shader.h \
		Render/headers/zs-math.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		World/headers/obj_properties.h \
		Scripting/headers/LuaScript.h \
		World/headers/terrain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-shader.o Render/zs-shader.cpp

zs-math.o: Render/zs-math.cpp Render/headers/zs-math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-math.o Render/zs-math.cpp

zs-pipeline.o: Render/zs-pipeline.cpp Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		Render/headers/zs-math.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		World/headers/obj_properties.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		Scripting/headers/LuaScript.h \
		World/headers/terrain.h \
		World/headers/2dtileproperties.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-pipeline.o Render/zs-pipeline.cpp

zs-mesh.o: Render/zs-mesh.cpp Render/headers/zs-mesh.h \
		Render/headers/zs-math.h \
		triggers.h \
		Misc/headers/zs_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-mesh.o Render/zs-mesh.cpp

zs-texture.o: Render/zs-texture.cpp Render/headers/zs-texture.h \
		triggers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-texture.o Render/zs-texture.cpp

World.o: World/World.cpp World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		World/headers/Misc.h \
		World/headers/obj_properties.h \
		Scripting/headers/LuaScript.h \
		World/headers/terrain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o World.o World/World.cpp

Misc.o: World/Misc.cpp World/headers/Misc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Misc.o World/Misc.cpp

InspectorWin.o: ProjEd/InspectorWin.cpp ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		ProjEd/headers/InspEditAreas.h \
		World/headers/World.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		ui_inspector_win.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InspectorWin.o ProjEd/InspectorWin.cpp

ProjCreateWin.o: ProjEd/ProjCreateWin.cpp ProjEd/headers/ProjCreateWin.h \
		mainwin.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		ui_proj_create_win.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProjCreateWin.o ProjEd/ProjCreateWin.cpp

zs-camera.o: World/zs-camera.cpp World/headers/zs-camera.h \
		Render/headers/zs-math.h \
		Misc/headers/oal_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-camera.o World/zs-camera.cpp

PropertyAreas.o: ProjEd/PropertyAreas.cpp ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		ProjEd/headers/InspEditAreas.h \
		World/headers/World.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PropertyAreas.o ProjEd/PropertyAreas.cpp

EdActions.o: ProjEd/EdActions.cpp ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EdActions.o ProjEd/EdActions.cpp

oal_manager.o: Misc/oal_manager.cpp Misc/headers/oal_manager.h \
		Render/headers/zs-math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oal_manager.o Misc/oal_manager.cpp

EditorUI.o: ProjEd/EditorUI.cpp ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		ui_editor.h \
		ui_inspector_win.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EditorUI.o ProjEd/EditorUI.cpp

ProjBuilder.o: Misc/ProjBuilder.cpp Misc/headers/ProjBuilder.h \
		Misc/headers/zs_types.h \
		ui_buildconsole.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProjBuilder.o Misc/ProjBuilder.cpp

LuaScript.o: Scripting/LuaScript.cpp Scripting/headers/zsensdk.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		Scripting/headers/LuaScript.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LuaScript.o Scripting/LuaScript.cpp

zsensdk.o: Scripting/zsensdk.cpp Scripting/headers/LuaScript.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		Scripting/headers/zsensdk.h \
		World/headers/obj_properties.h \
		World/headers/terrain.h \
		World/headers/2dtileproperties.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		Input/headers/zs-input.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zsensdk.o Scripting/zsensdk.cpp

MatShaderProps.o: Render/MatShaderProps.cpp Render/headers/MatShaderProps.h \
		Render/headers/zs-texture.h \
		Render/headers/zs-shader.h \
		Render/headers/zs-math.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Misc/headers/zs_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MatShaderProps.o Render/MatShaderProps.cpp

GameObject.o: World/GameObject.cpp World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		World/headers/Misc.h \
		World/headers/obj_properties.h \
		Scripting/headers/LuaScript.h \
		World/headers/terrain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameObject.o World/GameObject.cpp

go_filestream.o: World/GoProperty/go_filestream.cpp World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		World/headers/obj_properties.h \
		Scripting/headers/LuaScript.h \
		World/headers/terrain.h \
		World/headers/2dtileproperties.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		ProjEd/headers/InspEditAreas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o go_filestream.o World/GoProperty/go_filestream.cpp

go_properties.o: World/GoProperty/go_properties.cpp World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		World/headers/obj_properties.h \
		Scripting/headers/LuaScript.h \
		World/headers/terrain.h \
		World/headers/2dtileproperties.h \
		ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		ProjEd/headers/InspEditAreas.h \
		World/headers/Misc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o go_properties.o World/GoProperty/go_properties.cpp

tile_properties.o: World/GoProperty/tile_properties.cpp ProjEd/headers/ProjectEdit.h \
		ProjEd/headers/EdActions.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		ProjEd/headers/EditorSettings.h \
		Misc/headers/ProjBuilder.h \
		ui_buildconsole.h \
		Misc/headers/GlyphManager.h \
		Misc/headers/ThumbnailsMaster.h \
		World/headers/2dtileproperties.h \
		World/headers/obj_properties.h \
		Scripting/headers/LuaScript.h \
		World/headers/terrain.h \
		ProjEd/headers/InspEditAreas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tile_properties.o World/GoProperty/tile_properties.cpp

AssimpMeshLoader.o: Misc/AssimpMeshLoader.cpp Misc/headers/AssimpMeshLoader.h \
		triggers.h \
		Render/headers/zs-mesh.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AssimpMeshLoader.o Misc/AssimpMeshLoader.cpp

GizmosRenderer.o: Render/GizmosRenderer.cpp Render/headers/GizmosRenderer.h \
		Render/headers/zs-shader.h \
		Render/headers/zs-math.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Misc/headers/zs_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GizmosRenderer.o Render/GizmosRenderer.cpp

GlyphManager.o: Misc/GlyphManager.cpp Misc/headers/GlyphManager.h \
		Render/headers/zs-math.h \
		Misc/headers/EditorManager.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GlyphManager.o Misc/GlyphManager.cpp

EditorManager.o: Misc/EditorManager.cpp Misc/headers/EditorManager.h \
		Misc/headers/zs_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EditorManager.o Misc/EditorManager.cpp

zsensdk_input.o: Scripting/zsensdk_input.cpp Scripting/headers/LuaScript.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		Scripting/headers/zsensdk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zsensdk_input.o Scripting/zsensdk_input.cpp

EditorSettings.o: ProjEd/EditorSettings.cpp ProjEd/headers/EditorSettings.h \
		Misc/headers/EditorManager.h \
		Misc/headers/zs_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EditorSettings.o ProjEd/EditorSettings.cpp

TerrainUtils.o: World/TerrainUtils.cpp World/headers/obj_properties.h \
		World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		Scripting/headers/LuaScript.h \
		World/headers/terrain.h \
		World/headers/Misc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TerrainUtils.o World/TerrainUtils.cpp

Physics.o: World/Physics.cpp World/headers/World.h \
		ProjEd/headers/InspectorWin.h \
		Render/headers/zs-math.h \
		Misc/headers/zs_types.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Render/headers/zs-texture.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h \
		Render/headers/MatShaderProps.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h \
		World/headers/obj_properties.h \
		Scripting/headers/LuaScript.h \
		World/headers/terrain.h \
		ProjEd/headers/InspEditAreas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Physics.o World/Physics.cpp

ThumbnailsMaster.o: Misc/ThumbnailsMaster.cpp Misc/headers/ThumbnailsMaster.h \
		Render/headers/zs-shader.h \
		Render/headers/zs-math.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-texture.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Misc/headers/zs_types.h \
		Render/headers/MatShaderProps.h \
		Render/headers/zs-pipeline.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ThumbnailsMaster.o Misc/ThumbnailsMaster.cpp

zs-animation.o: Render/zs-animation.cpp Render/headers/zs-animation.h \
		Render/headers/zs-math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-animation.o Render/zs-animation.cpp

zs3m-master.o: Misc/zs3m-master.cpp Misc/headers/zs3m-master.h \
		Render/headers/zs-math.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Misc/headers/zs_types.h \
		Misc/headers/AssimpMeshLoader.h \
		Render/headers/zs-animation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs3m-master.o Misc/zs3m-master.cpp

zs-uiwidget.o: ui/zs-uiwidget.cpp ui/headers/zs-uiwidget.h \
		Input/headers/zs-input.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-uiwidget.o ui/zs-uiwidget.cpp

zs-uibutton.o: ui/zs-uibutton.cpp ui/headers/zs-uibutton.h \
		Render/headers/zs-texture.h \
		ui/headers/zs-uiwidget.h \
		Render/headers/zs-pipeline.h \
		Render/headers/zs-shader.h \
		Render/headers/zs-math.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h \
		Render/headers/zs-mesh.h \
		triggers.h \
		Misc/headers/zs_types.h \
		Render/headers/GizmosRenderer.h \
		Misc/headers/EditorManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-uibutton.o ui/zs-uibutton.cpp

zs-material-defines.o: Render/zs-material-defines.cpp Render/headers/MatShaderProps.h \
		Render/headers/zs-texture.h \
		Render/headers/zs-shader.h \
		Render/headers/zs-math.h \
		World/headers/zs-camera.h \
		Misc/headers/oal_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-material-defines.o Render/zs-material-defines.cpp

zs-input.o: Input/zs-input.cpp Input/headers/zs-input.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-input.o Input/zs-input.cpp

moc_mainwin.o: moc_mainwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwin.o moc_mainwin.cpp

moc_ProjectEdit.o: moc_ProjectEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ProjectEdit.o moc_ProjectEdit.cpp

moc_InspectorWin.o: moc_InspectorWin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InspectorWin.o moc_InspectorWin.cpp

moc_ProjCreateWin.o: moc_ProjCreateWin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ProjCreateWin.o moc_ProjCreateWin.cpp

moc_ProjBuilder.o: moc_ProjBuilder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ProjBuilder.o moc_ProjBuilder.cpp

moc_InspEditAreas.o: moc_InspEditAreas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InspEditAreas.o moc_InspEditAreas.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ZSpireGameEd/bin || mkdir -p $(INSTALL_ROOT)/opt/ZSpireGameEd/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ZSpireGameEd/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/ZSpireGameEd/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ZSpireGameEd/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ZSpireGameEd/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

